{% set name = "sos-notebook" %}
{% set version = "0.22.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/0d/bb/21dc8031d64f70cd583be2e2814bfd4ad8a88bef328961c5a10f2ce4e63a/sos-notebook-0.22.6.tar.gz
  sha256: c1b8afa940029d223a1c8b9a6cee75a1d06b58c3f6ad7763f0facab4f59cb315

build:
  number: 0
  skip: true  # [py<37]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
    - {{ PYTHON }} -m sos_notebook.install --sys-prefix

requirements:
  host:
    - ipython
    - notebook >=5.0.0
    - pip
    - python
    - setuptools
    - jupyter_contrib_core
  run:
    - ipykernel
    - ipython
    - markdown
    # see https://github.com/conda-forge/sos-notebook-feedstock/issues/43
    # - matplotlib-base
    - nbconvert >=6.0.1
    - nbformat
    - notebook >=5.0.0
    - graphviz
    - python-graphviz
    - pillow
    - pandas
    - prometheus_client
    - prompt_toolkit
    - python
    - jupyter_client >=6.1
    - jinja2 <=2.11
    - sos >=0.19.2
    - tabulate

test:
  requires:
    - nose
    - pytest
    - selenium
  imports:
    - sos_notebook
  commands:
    - jupyter kernelspec list | grep -w $PREFIX/share/jupyter/kernels/sos  # [unix]
    - jupyter kernelspec list | findstr \share\jupyter\kernels\sos  # [win]
    - jupyter run --kernel=sos ex.py
  files:
    - ex.py

about:
  home: https://github.com/vatlab/SOS
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Script of Scripts (SoS): an interactive, cross-platform, and cross-language workflow system for reproducible data analysis'
  doc_url: https://vatlab.github.io/sos-docs/
  dev_url: https://github.com/vatlab/sos-notebook

extra:
  recipe-maintainers:
    - BoPeng
    - gaow
    - jdblischak
